from typing import Optional
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    PROJECT_NAME: str = "Personalized Quiz Service"
    ENVIRONMENT: str = "development"

    DATABASE_URL: str

    GROQ_API_KEY: str
    GROQ_MODEL: str = "llama3-70b-8192"
    GROQ_MAX_RETRIES: int = 2
    GROQ_RETRY_BASE_DELAY_SECONDS: float = 1.0

    CLERK_JWKS_URL: str
    CLERK_ISSUER: str
    CLERK_AUDIENCE: Optional[str] = None
    AUTH_BYPASS: bool = False
    ADMIN_CLERK_IDS: str = ""

    ANALYTICS_ABANDONED_AFTER_HOURS: int = 24
    ANALYTICS_TOPIC_MIN_ATTEMPTS: int = 3
    ANALYTICS_MAX_TOPICS_PER_SUBJECT: int = 10

    ANALYTICS_MAX_VALID_RESPONSE_TIME_SECONDS: float = 600.0
    ANALYTICS_BEHAVIOR_MIN_ATTEMPTS: int = 5
    ANALYTICS_ACCURATE_THRESHOLD: float = 70.0
    ANALYTICS_MEDIAN_FALLBACK_SECONDS: float = 10.0
    ANALYTICS_BALANCED_TIME_RATIO: float = 0.15

    ANALYTICS_TREND_SESSION_WINDOW: int = 5
    ANALYTICS_TREND_MIN_ATTEMPTS_PER_PERIOD: int = 1
    ANALYTICS_TREND_CHANGE_THRESHOLD: float = 5.0

    # These five mastery weights should add up to 1.0 — nothing enforces
    # that automatically, so keep it in mind if you tweak them.
    ANALYTICS_MASTERY_ACCURACY_WEIGHT: float = 0.35
    ANALYTICS_MASTERY_RECENT_PERFORMANCE_WEIGHT: float = 0.25
    ANALYTICS_MASTERY_DIFFICULTY_WEIGHT: float = 0.15
    ANALYTICS_MASTERY_RETENTION_WEIGHT: float = 0.15
    ANALYTICS_MASTERY_CONSISTENCY_WEIGHT: float = 0.10
    ANALYTICS_MASTERY_MIN_ATTEMPTS: int = 5
    ANALYTICS_MASTERY_NEUTRAL_SCORE: float = 50.0
    ANALYTICS_MASTERY_CONSISTENCY_MIN_SESSIONS: int = 3
    ANALYTICS_MASTERY_DEVELOPING_THRESHOLD: float = 40.0
    ANALYTICS_MASTERY_PROFICIENT_THRESHOLD: float = 70.0
    ANALYTICS_MASTERY_ADVANCED_THRESHOLD: float = 85.0

    # Same deal — these four growth weights should add up to 1.0.
    ANALYTICS_GROWTH_IMPROVEMENT_WEIGHT: float = 0.40
    ANALYTICS_GROWTH_CONSISTENCY_WEIGHT: float = 0.25
    ANALYTICS_GROWTH_EFFORT_WEIGHT: float = 0.20
    ANALYTICS_GROWTH_MASTERY_WEIGHT: float = 0.15
    ANALYTICS_GROWTH_GROWING_THRESHOLD: float = 40.0
    ANALYTICS_GROWTH_STRONG_THRESHOLD: float = 70.0
    ANALYTICS_GROWTH_EXCEPTIONAL_THRESHOLD: float = 85.0
    ANALYTICS_GROWTH_WINDOW_DAYS: int = 30
    ANALYTICS_GROWTH_MIN_ATTEMPTS_IN_WINDOW: int = 3
    ANALYTICS_GROWTH_EFFORT_TARGET_QUIZZES: int = 20
    ANALYTICS_GROWTH_EFFORT_TARGET_QUESTIONS: int = 150
    ANALYTICS_GROWTH_EFFORT_TARGET_WEAK_TOPIC_ATTEMPTS: int = 10

    ANALYTICS_RECOMMENDATION_MAX_COUNT: int = 5
    ANALYTICS_RECOMMENDATION_REPEATED_MISTAKES_THRESHOLD: int = 2
    ANALYTICS_RECOMMENDATION_ABANDONMENT_THRESHOLD: float = 20.0
    ANALYTICS_RECOMMENDATION_ACCURACY_WEIGHT: float = 1.0
    ANALYTICS_RECOMMENDATION_ATTEMPTS_WEIGHT: float = 0.5
    ANALYTICS_RECOMMENDATION_ATTEMPTS_CAP: int = 50
    ANALYTICS_RECOMMENDATION_REPEATED_MISTAKES_WEIGHT: float = 5.0
    ANALYTICS_RECOMMENDATION_MASTERY_WEIGHT: float = 0.5
    ANALYTICS_RECOMMENDATION_RECENCY_WEIGHT: float = 0.3
    ANALYTICS_RECOMMENDATION_RECENCY_HALF_LIFE_DAYS: float = 14.0

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=True,
        extra="ignore",
    )


settings = Settings()
